export const USER = {
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    ADD_UNREAD_MESSAGE: 'ADD_UNREAD_MESSAGE'
};

export const POST = {
    FETCH_POST_LIST_PENDING: 'FETCH_POST_LIST_PENDING',
    FETCH_POST_LIST_SUCCESS: 'FETCH_POST_LIST_SUCCESS',
    FETCH_POST_LIST_FAILURE: 'FETCH_POST_LIST_FAILURE',
    FETCH_POST_SINGLE_PENDING: 'FETCH_POST_SINGLE_PENDING',
    FETCH_POST_SINGLE_SUCCESS: 'FETCH_POST_SINGLE_SUCCESS',
    FETCH_POST_SINGLE_FAILURE: 'FETCH_POST_SINGLE_FAILURE',
    NEW_POST_PENDING: 'NEW_POST_PENDING',
    NEW_POST_SUCCESS: 'NEW_POST_SUCCESS',
    NEW_POST_FAILURE: 'NEW_POST_FAILURE',
    VOTE_POST_PENDING: 'VOTE_POST_PENDING',
    VOTE_POST_FAILURE: 'VOTE_POST_FAILURE',
    VOTE_POST_SUCCESS: 'VOTE_POST_SUCCESS',
    RESET_POST: 'RESET_POST'
};

export const COMMENT = {
    FETCH_COMMENT_LIST_PENDING: 'FETCH_COMMENT_LIST_PENDING',
    FETCH_COMMENT_LIST_SUCCESS: 'FETCH_COMMENT_LIST_SUCCESS',
    FETCH_COMMENT_LIST_FAILURE: 'FETCH_COMMENT_LIST_FAILURE',
    FETCH_MORE_COMMENTS_PENDING: 'FETCH_MORE_COMMENTS_PENDING',
    FETCH_MORE_COMMENTS_SUCCESS: 'FETCH_MORE_COMMENTS_SUCCESS',
    FETCH_MORE_COMMENTS_FAILURE: 'FETCH_MORE_COMMENTS_FAILURE',
    VOTE_COMMENT_PENDING: 'VOTE_COMMENT_PENDING',
    VOTE_COMMENT_FAILURE: 'VOTE_COMMENT_FAILURE',
    VOTE_COMMENT_SUCCESS: 'VOTE_COMMENT_SUCCESS',
    NEW_COMMENT_PENDING: 'NEW_COMMENT_PENDING',
    NEW_COMMENT_FAILURE: 'NEW_COMMENT_FAILURE',
    NEW_COMMENT_SUCCESS: 'NEW_COMMENT_SUCCESS'
};

export const SUBREDDIT = {
    FETCH_SUBREDDIT_LIST_PENDING: 'FETCH_SUBREDDIT_LIST_PENDING',
    FETCH_SUBREDDIT_LIST_SUCCESS: 'FETCH_SUBREDDIT_LIST_SUCCESS',
    FETCH_SUBREDDIT_LIST_FAILURE: 'FETCH_SUBREDDIT_LIST_FAILURE',
    FETCH_SUBREDDIT_SINGLE_PENDING: 'FETCH_SUBREDDIT_SINGLE_PENDING',
    FETCH_SUBREDDIT_SINGLE_SUCCESS: 'FETCH_SUBREDDIT_SINGLE_SUCCESS',
    FETCH_SUBREDDIT_SINGLE_FAILURE: 'FETCH_SUBREDDIT_SINGLE_FAILURE',
    NEW_SUBREDDIT_PENDING: 'NEW_SUBREDDIT_PENDING',
    NEW_SUBREDDIT_SUCCESS: 'NEW_SUBREDDIT_SUCCESS',
    NEW_SUBREDDIT_FAILURE: 'NEW_SUBREDDIT_FAILURE',
    ALTER_RULE: 'ALTER_RULE',
    ALTER_SUSPENSION: 'ALTER_SUSPENSION'
};

export const MODERATOR = {
    FETCH_MODERATOR_PENDING: 'FETCH_MODERATOR_PENDING',
    FETCH_MODERATOR_FAILURE: 'FETCH_MODERATOR_FAILURE',
    FETCH_MODERATOR_SUCCESS: 'FETCH_MODERATOR_SUCCESS',
    SUSPEND_USER_PENDING: 'SUSPEND_USER_PENDING',
    SUSPEND_USER_FAILURE: 'SUSPEND_USER_FAILURE',
    SUSPEND_USER_SUCCESS: 'SUSPEND_USER_SUCCESS',
    UNSUSPEND_USER_PENDING: 'UNSUSPEND_USER_PENDING',
    UNSUSPEND_USER_FAILURE: 'UNSUSPEND_USER_FAILURE',
    UNSUSPEND_USER_SUCCESS: 'UNSUSPEND_USER_SUCCESS',
    ALTER_RULE_PENDING: 'ALTER_RULE_PENDING',
    ALTER_RULE_FAILURE: 'ALTER_RULE_FAILURE',
    ALTER_RULE_SUCCESS: 'ALTER_RULE_SUCCESS'
}